# Generated by Django 3.0.6 on 2020-06-02 06:45

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20200602_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='Asia/Kolkata'),
        ),
    ]
