# Generated by Django 3.0.6 on 2020-06-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20200602_1005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityperiod',
            unique_together={('users', 'start_time', 'end_time')},
        ),
    ]
